[tool.black]
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-safe-fixes = [
  "D",
  "TCH",
  "FLY",
  "SIM",
  "ANN",
  "FA102",
  "UP"
]
ignore = [
  "CPY001",  # TODO
  "FBT",  # TODO: Boolean in function definition
  "COM",  # CONFIG: No trailing commas
  "PT",  # CONFIG: Not using pytest
  "D203",  # CONFIG: incompatible with D211
  "D212",  # CONFIG: incompatible with D213
  "FIX002",  # CONFIG: we use TODO
  "TD002",  # CONFIG: no detailed TODO documentation is required
  "TD003",  # CONFIG: no detailed TODO documentation is required
  "S603",  # CONFIG: `subprocess` call: check for execution of untrusted input
  "S607",  # CONFIG: executing system installed tools
  "D206",  # CONFIG: formatter
  'ISC001',  # CONFIG: formatter
  'Q000',  # CONFIG: formatter
  'Q001',  # CONFIG: formatter
  'Q002',  # CONFIG: formatter
  'Q003',  # CONFIG: formatter
  'W191',  # CONFIG: formatter
  "ANN",  # TODO: we are missing many annotations
  "ARG001",  # TODO: Unused function argument (mostly for API compatibility)
  "ARG002",  # TODO: Unused method argument (mostly for API compatibility)
  "PTH",  # TODO: Not using pathlib
  "BLE001",  # WONTFIX: Do not catch blind exception: `Exception`, third-party modules do not have defined exceptions
  "EM",  # TODO: Exception strings
  "D10",  # TODO: we are missing many docstrings
  "DJ001",  # TODO: Avoid using `null=True` on string-based fields such as CharField (maybe add noqa)
  "DOC501",  # TODO: Raised exception missing from docstring
  "TRY003",  # WONTFIX: Avoid specifying long messages outside the exception class
  "PLR0912",  # WONTFIX: Too many branches
  "PLR6301",  # TODO: Method could be a function, class method, or static method
  "PLR2004",  # TODO: Magic value used in comparison, consider replacing 201 with a constant variable
  "PLR0904",  # TODO: Too many public methods
  "RUF001",  # WONTFIX: String contains ambiguous unicode character, we are using Unicode
  "RUF012",  # TODO: Mutable class attributes should be annotated with `typing.ClassVar`
  "E501",  # WONTFIX: we accept long strings (rest is formatted by black)
  "PLW1514",  # TODO: `open` in text mode without explicit `encoding` argument
  "N818",  # TODO: exception naming
  "FURB113",  # TODO: Use `image.extend(...)` instead of repeatedly calling `image.append()`
  "SLF001"  # TODO: Private member accessed (might need noqa tags)
]
preview = true
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 16

[tool.ruff.lint.per-file-ignores]
"payments/backends.py" = ["T201"]
"scripts/*" = ["T201"]
